### ISSUE TITLE
Support for Laravel 7?

### ISSUE THREAD

**Issue by dont-panic-42** [mrgswift/laravel-encryptenv#1]
I guess this is a feature request rather than an issue.  This looks excellent, exactly what I am looking for, however AFAICT it does not support Laravel 7.  Do you plan to add that support?

**Comment by mrgswift** [comment]
I will look into it.  I haven't tested it yet in Laravel 7 but I do plan on adding support for Laravel 7.  I have been completely slammed lately.  I will get to it sometime this month, but feel free to do a pull request.

**Comment by mrgswift** [comment]
@dont-panic-42 I just released v1.0.3 which now has Laravel 7 support.

**Comment by dont-panic-42** [comment]
Thank you!
