### ISSUE TITLE
Its not workin in artisan

### ISSUE THREAD

**Issue by faisal-mahmood-hyphen** [mrgswift/laravel-encryptenv#10]
its not working in artisan i have try to migrate command its return null value

**Comment by mrgswift** [comment]
@faisal-mahmood-hyphen 
Starting with v1.0.8, you are now able to run console commands using your CONFIGKEY.  A new console command `artisan encryptenv:console` was added for you to run your own console commands.  I tested this with Laravel scheduler and commands like php artisan migrate.  These commands tested successfully and were able to query and write to the database when the database env variables are encrypted.  I updated the README with the new console command and how to use it.
