### ISSUE TITLE
Error while run the queue

### ISSUE THREAD

**Issue by shailendra-fxbytes** [mrgswift/laravel-encryptenv#14]
I have using this package the encrypt the env its working fine on all things.

Only issue i am getting when i run laravel queue with supervisor it give continues error and making the logs too fill all time the error is:- 
'artisan' 'queue:work' '--sleep=3' '--tries=3' '--timeout=900'" exceeded the timeout of 60 seconds. {"exception":"[object]
(Symfony\\Component\\Process\\Exception\\ProcessTimedOutException(code: 0): The process \"'php' '/artisan' 'queue:work' '--sleep=3' '--tries=3' '--timeout=900'\" exceeded the timeout
of 60 seconds. at [FOLDER_PATH]/vendor/symfony/process/Process.php:1158)

I have added timeout of 900 but still it gives error. It may be due to i have added something wrong way. 
Below is the code for supervisor

process_name=%(program_name)s_%(process_num)02d
command=php [FOLDER_PATH]/artisan encryptenv:console 'php [FOLDER_PATH]/artisan queue:work --sleep=3 --tries=3 --timeout=900' [KEY]
autostart=true
autorestart=true
user=[USER]
numprocs=2
redirect_stderr=true
stdout_logfile=[FOLDER_PATH]worker.log

Can you please help me out here and let me know to overcome this issue.

**Comment by mrgswift** [comment]
The error message seems to indicate that [FOLDER_PATH] isn't defined?

"The process "'php' '/artisan' 'queue:work' '--sleep=3' '--tries=3' '--timeout=900'" exceeded the timeout
of 60 seconds. at [FOLDER_PATH]/vendor/symfony/process/Process.php:1158)"

Specifically ""The process "'php' **'/artisan'** 'queue:work' '--sleep=3' '--tries=3' '--timeout=900'" exceeded the timeout"

Did you replace the actual folder path in your issue post/message above for security reasons or is it actually missing?

**Comment by mrgswift** [comment]
Closing after no response for months

**Comment by shailendra-kbtechnology** [comment]
@mrgswift Hello i am just pasting the folder path here for security reasons only in the supervisor i have define the path. Can you please let me know what could be the solution for this

**Comment by shailendra-kbtechnology** [comment]
@mrgswift any update?

**Comment by zulfajuniadi** [comment]
We had the same issue as described above. After implementing encryption, we had to do the following in order for for it to work:

For jobs running in supervisord, in `/etc/supervisord.conf`:
```
[supervisord]
...
environment=APP_CONFIGKEY="xxxx"
```

For cron, we needed to add `APP_CONFIGKEY="xxxx"` in the `/etc/environment` file.
