### ISSUE TITLE
Installation Error on Laravel 5.8.*

### ISSUE THREAD

**Issue by arung-in** [mrgswift/laravel-encryptenv#2]
composer require mrgswift/laravel-encryptenv

this comment takes too much time on laravel : 5.8.* and finally not installed message

![env](https://user-images.githubusercontent.com/11191957/85259797-489c2a00-b487-11ea-9fbd-6326aedccd0f.png)

**Comment by mrgswift** [comment]
This seems like more of an issue with your composer configuration.  Is your packagist repository URL using https:// ?

**More on this here:**

https://gist.github.com/oanhnn/112f68e5b91a7dac7641bcd8b0ab13ac

-OR-

http://qodrbee.com/online/web-programming/solved-composer-content-length-mismatch/
