### ISSUE TITLE
Application work but Migrations/ Commands / Seeders are no longer working

### ISSUE THREAD

**Issue by dainius-s** [mrgswift/laravel-encryptenv#5]
I have managed to setup the app and it works great. 

Except when you need to migrate / run command or seed tables. In a way defeat the purpose as it means you can no longer make any changes or updated to schema at all trough Laravel commands.

Has anyone experienced this or know how to fix it?

**Comment by dainius-s** [comment]
It was due to running command in windows environment and not on virtual box

**Comment by mrgswift** [comment]
@dainius-s 

Start with v1.0.8, you are now able to run console commands using your CONFIGKEY.  A new console command `artisan encryptenv:console` was added for you to run your own console commands.  I tested this with Laravel scheduler and commands like php artisan migrate.  These commands tested successfully and were able to query and write to the database when the database env variables are encrypted.  I updated the README with the new console command and how to use it.
